name: Update rock

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * *'

jobs:
  update:
    name: Update rock
    strategy:
      fail-fast: false
      matrix:
        rock-path:
          - chaos-exporter
          - chaos-operator
          - litmusportal-event-tracker
          - litmusportal-subscriber
    uses: canonical/observability/.github/workflows/rock-update.yaml@feat/support-rock-monorepos
    with:
      rock-path: ${{ matrix.rock-path }}
